id: I8BB660BB
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:59:28.737128'
last_modified: '2022-05-30T22:59:28.737135'
parser: null
source_metadata:
  title: Rogza Sönam Palge
  language: bo
  description: 'Texts by and about Rogza Sönam Palge (rog bza'' bsod nams dpal dge,
    1800–1884):'
  volume:
    fAF1D:
      title: In Praise of Sönam Palge
      base_file: fAF1D.txt
      order: 1
      parent: Praise
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
